# Generated by Django 3.1.8 on 2022-01-08 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0064_auto_20220108_1501'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('contact_data_email', models.EmailField(default='example@mail.com', max_length=254, verbose_name='Email для связи')),
                ('contact_data_phone', phonenumber_field.modelfields.PhoneNumberField(default='+380999999999', max_length=128, region='UA', verbose_name='Контактный номер')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_page', to='website_admin_api.homepage', verbose_name='Домашняя страница для страницы команды')),
            ],
            options={
                'verbose_name': 'Команда',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('competence', models.TextField(max_length=510, verbose_name='Cфера компетенции')),
                ('professional_credo', models.TextField(max_length=510, verbose_name='Профессиональное кредо')),
                ('additional_information', models.TextField(max_length=1000, verbose_name='Дополнительная информация')),
                ('photo_caption', models.CharField(blank=True, max_length=250, verbose_name='Подпись к изображению')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='website_admin_api.teampage', verbose_name='Страница команды')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='wagtailimages.image', verbose_name='Фото учасника команды')),
            ],
            options={
                'verbose_name': 'Участник команды',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsPublicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_publication_page', to='website_admin_api.homepage', verbose_name='Домашння страница для страницы "Новости"')),
            ],
            options={
                'verbose_name': 'Страница "Новости"',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPublication',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('publication_title', models.CharField(max_length=255, verbose_name='Название публикации/новости')),
                ('publication_text', models.TextField(max_length=10000, verbose_name='Текст публикации/новости')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации/новости')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания публикации/новости')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения публикации/новости')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к изображению')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_publications', to='website_admin_api.newspublicationpage', verbose_name='Домашння страница для страницы "Новости/Публикации')),
                ('publication_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Отдельная Новость',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя представителя компании')),
                ('email', models.EmailField(blank=True, default='example@mail.com', max_length=254, verbose_name='Email для связи')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+380999999999', max_length=128, region='UA', verbose_name='Контактный номер')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_page', to='website_admin_api.homepage', verbose_name='Домашняя страница для страницы "Контакты"')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
            bases=('wagtailcore.page',),
        ),
    ]
