# Generated by Django 3.1.8 on 2021-05-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0061_auto_20210423_1203'),
        ('website_admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompanypage',
            options={'verbose_name': 'О компании'},
        ),
        migrations.AlterModelOptions(
            name='activitiespage',
            options={'verbose_name': 'Страница "услуги / направления деятельности"'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='newspublication',
            options={'verbose_name': 'Отдельная Новость/Публикация'},
        ),
        migrations.AlterModelOptions(
            name='newspublicationtag',
            options={'verbose_name': 'Новости/Публикации'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Участник команды'},
        ),
        migrations.AlterModelOptions(
            name='teampage',
            options={'verbose_name': 'Команда'},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='id',
        ),
        migrations.AddField(
            model_name='teammember',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=9, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
