# Generated by Django 3.1.8 on 2021-05-02 17:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0061_auto_20210423_1203'),
        ('website_admin_api', '0002_auto_20210502_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_page', to='website_admin_api.homepage', verbose_name='Домашняя страница для страницы "Контакты"')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subject_of_request', models.CharField(max_length=255, verbose_name='Компетенция представителя')),
                ('subject_of_request_ru', models.CharField(max_length=255, null=True, verbose_name='Компетенция представителя')),
                ('subject_of_request_uk', models.CharField(max_length=255, null=True, verbose_name='Компетенция представителя')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя представителя компании')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='Полное имя представителя компании')),
                ('full_name_uk', models.CharField(max_length=255, null=True, verbose_name='Полное имя представителя компании')),
                ('email', models.EmailField(blank=True, default='example@mail.com', max_length=254, verbose_name='Email для связи')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+380999999999', max_length=128, region='UA', verbose_name='Контактный номер')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='website_admin_api.contactspage', verbose_name='Елементы списка контактов')),
            ],
            options={
                'verbose_name': 'Елемент списка контактов',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
