# Generated by Django 3.1.8 on 2021-05-02 17:45

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_api', '0003_contacts_contactspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='website_admin_api.contactspage', verbose_name='Елементы списка контактов'),
        ),
    ]
