# Generated by Django 3.1.8 on 2021-05-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0061_auto_20210423_1203'),
        ('website_admin_api', '0004_auto_20210502_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={},
        ),
        migrations.RemoveField(
            model_name='activities',
            name='id',
        ),
        migrations.AddField(
            model_name='activities',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=9999, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
