# Generated by Django 3.1.8 on 2021-05-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_api', '0005_auto_20210510_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name': 'Услуга / направление деятельности"', 'verbose_name_plural': 'Услуги / направления деятельности"'},
        ),
    ]
