# Generated by Django 3.1.8 on 2021-05-10 16:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_api', '0006_auto_20210510_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='website_admin_api.activitiespage', verbose_name='Страница Видов деятельности'),
        ),
    ]
