# Generated by Django 3.1.8 on 2021-05-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_api', '0007_auto_20210510_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompanypage',
            options={'verbose_name': 'Страница "О компании"'},
        ),
        migrations.AlterModelOptions(
            name='newspublicationpage',
            options={'verbose_name': 'Страница "Новости"'},
        ),
    ]
