# Generated by Django 3.1.8 on 2021-05-10 16:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_admin_api', '0008_auto_20210510_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspublication',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_publications', to='website_admin_api.newspublicationpage', verbose_name='Домашння страница для страницы "Новости/Публикации'),
        ),
    ]
